import { writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { buildHandlers } from '../src/browser/handlers/index.js';
import { VERSION } from '../src/version.js';

const handlers = buildHandlers(() => {}, async () => null);
const names = Object.keys(handlers).sort();

const groups: Record<string, string[]> = {};
for (const n of names) {
  const prefix = n.includes('.') ? n.split('.')[0] : 'misc';
  (groups[prefix] ??= []).push(n);
}

const lines: string[] = [];
lines.push('# Browser Bridge — API Reference');
lines.push('');
lines.push(`Version documentée : \`${VERSION}\`.`);
lines.push('');
lines.push('Commandes JSON-RPC exposées via WebSocket sur `/ws/browser-bridge`.');
lines.push('');
lines.push('Format de requête :');
lines.push('');
lines.push('```json');
lines.push('{ "id": "<id>", "type": "<command>", "payload": { ... } }');
lines.push('```');
lines.push('');
lines.push(`**Total : ${names.length} commandes**`);
lines.push('');
lines.push('## Authentification');
lines.push('');
lines.push('- `BRIDGE_TOKEN` : header `Authorization: Bearer <token>` (ou `?token=`). Obligatoire si `BRIDGE_HOST` n\'est pas local.');
lines.push('- `BRIDGE_ALLOWED_ORIGINS` : CSV d\'origines autorisées (rejet sinon)');
lines.push('- `BRIDGE_ALLOW_EXEC_SCRIPT=1` + `BRIDGE_ADMIN_TOKEN` : requis pour `exec.script`, token à fournir dans le payload (`adminToken`)');
lines.push('- `BRIDGE_ALLOW_FILE_URLS=1` + `BRIDGE_ALLOWED_FILE_ROOTS` : requis pour naviguer vers `file:`.');
lines.push('');
lines.push('## MCP');
lines.push('');
lines.push('Serveur MCP officiel via stdio : `npm run mcp` ou `openclaw-mcp` après build.');
lines.push('');
lines.push('Outils MCP principaux : `browser_status`, `navigate`, `annotate_page`, `click_ref`, `type_ref`, `extract_schema`, `human_timing_get`, `human_timing_set`, `human_antispam_check`. Outil bas niveau `browser_command` activable via `BRIDGE_MCP_ALLOW_RAW=1`.');
lines.push('');
lines.push('Les outils `human_timing_get`, `human_timing_set` et `human_antispam_check` sont prévus pour les agents : ils permettent d\'adapter la cadence en cours de session sans exposer toute l\'API brute.');
lines.push('');
lines.push('Ressource MCP : `api` (`openclaw://api`) expose la liste des commandes bridge enregistrées. Prompt MCP : `browser_task` fournit un canevas de tâche navigateur orienté refs.');
lines.push('');
lines.push('## Commandes par catégorie');
lines.push('');

for (const grp of Object.keys(groups).sort()) {
  lines.push(`### \`${grp}\``);
  lines.push('');
  for (const n of groups[grp].sort()) {
    lines.push(`- \`${n}\``);
  }
  lines.push('');
}

lines.push('## Commandes utiles');
lines.push('');
lines.push('### `dom.visibleText`');
lines.push('');
lines.push('Extrait le texte réellement visible dans le DOM, élément par élément, même quand le contenu n\'est pas exposé comme lien, bouton ou article. Utile pour des pages JavaScript comme Google Maps où un téléphone peut apparaître dans un simple `div` visible.');
lines.push('');
lines.push('Payload :');
lines.push('');
lines.push('```json');
lines.push('{');
lines.push('  "query": ".optional-root-css-selector",');
lines.push('  "textFilter": "Numéro|06|Adresse",');
lines.push('  "filterAny": ["Numéro", "06", "Adresse"],');
lines.push('  "filterLines": true,');
lines.push('  "limit": 100,');
lines.push('  "includeHidden": false');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('`textFilter` reste une expression régulière. Sur Windows/PowerShell, préférez `filterAny` ou `--filter-any=a,b,c` pour éviter que `cmd.exe` interprète `|` comme un pipeline avant que Node reçoive l\'argument. `filterLines` filtre ligne par ligne après extraction.');
lines.push('');
lines.push('Réponse :');
lines.push('');
lines.push('```json');
lines.push('{ "type": "visible-text", "count": 1, "items": [{ "text": "06 58 47 70 24", "tag": "div", "selector": "div.Io6YTe.fontBodyMedium.kR99db", "box": { "x": 500, "y": 662, "w": 402, "h": 40 } }] }');
lines.push('```');
lines.push('');
lines.push('CLI :');
lines.push('');
lines.push('```bash');
lines.push('node bridge-cli.cjs visibleText --filter-any=Numéro,06,Adresse --filter-lines --limit=50');
lines.push('# alias accepté');
lines.push('node bridge-cli.cjs visible-text --filter-any=Numéro,06,Adresse --filter-lines --limit=50');
lines.push('```');
lines.push('');
lines.push('### `dom.extract` avec `type: "listings"`');
lines.push('');
lines.push('Extrait une liste structurée depuis des cartes de résultats, annuaires, Google Maps, Pages Jaunes ou pages de listings génériques.');
lines.push('');
lines.push('Payload :');
lines.push('');
lines.push('```json');
lines.push('{ "type": "listings" }');
lines.push('```');
lines.push('');
lines.push('Réponse :');
lines.push('');
lines.push('```json');
lines.push('{');
lines.push('  "type": "listings",');
lines.push('  "listings": [');
lines.push('    {');
lines.push('      "name": "Ottho - Formation No Code et IA",');
lines.push('      "rating": 5,');
lines.push('      "reviews": 186,');
lines.push('      "address": "11 Rue Montgrand, Marseille",');
lines.push('      "phone": "07 57 59 77 84",');
lines.push('      "website": "https://...",');
lines.push('      "hours": "Ouvert · Ferme à 18:00",');
lines.push('      "summary": "Excellente expérience..."');
lines.push('    }');
lines.push('  ]');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('CLI :');
lines.push('');
lines.push('```bash');
lines.push('node bridge-cli.cjs extract listings');
lines.push('```');
lines.push('');
lines.push('### Capacités humaines');
lines.push('');
lines.push('- `human.timing.get` retourne le profil de timings de consultation actif.');
lines.push('- `human.timing.set` ajuste à chaud les timings (`consultSpeed`, WPM, min/max, cadence de feedback) pour ralentir ou accélérer les consultations sans redémarrage.');
lines.push('- `human.timing.reset` restaure le profil par défaut.');
lines.push('- `human.antispam.check` inspecte la page et renvoie un warning structuré au lieu de lancer une erreur.');
lines.push('- `human.scan` lit le texte visible, scrolle lentement, puis relit. Il accepte `textFilter`, `filterAny`, et `filterLines`.');
lines.push('- `human.findText` cherche un texte visible et scrolle si besoin, avec un timeout global borné via `timeoutMs`.');
lines.push('- `human.clickText` cherche un texte visible, logue les étapes (`finding`, `coordinates`, `clicking`) et clique au centre de l\'élément trouvé. Si le clic coordonné échoue, il tente un fallback par `agent.click` sur un ref annoté.');
lines.push('- `human.idle` déplace doucement la souris et marque des pauses de lecture.');
lines.push('- `human.jitter` ajoute de petites hésitations autour de la position courante.');
lines.push('- `human.skim` parcourt une page avec scrolls progressifs, pauses et petits retours en arrière.');
lines.push('- `human.backtrack` remonte légèrement, utile quand un humain relit une zone.');
lines.push('- `human.focusCycle` parcourt les éléments focusables au clavier avec `Tab`.');
lines.push('- `human.goBack` / `human.goForward` utilisent l\'historique avec pause humaine.');
lines.push('');
lines.push('CLI :');
lines.push('');
lines.push('```bash');
lines.push('node bridge-cli.cjs scan --steps=4 --filter-any=Restaurant,Adresse,Numéro');
lines.push('node bridge-cli.cjs find-text "Le Ramus"');
lines.push('node bridge-cli.cjs click-text "Le Ramus" --timeout-ms=15000');
lines.push('node bridge-cli.cjs idle 2500');
lines.push('node bridge-cli.cjs jitter 18 4');
lines.push('node bridge-cli.cjs skim 4 420');
lines.push('node bridge-cli.cjs backtrack');
lines.push('node bridge-cli.cjs focus-cycle 3');
lines.push('node bridge-cli.cjs timing get');
lines.push('node bridge-cli.cjs timing set consultSpeed=1.6 minFocusedMs=3500 feedbackIntervalMs=800');
lines.push('node bridge-cli.cjs antispam');
lines.push('```');
lines.push('');

lines.push('### Profil de timing humain');
lines.push('');
lines.push('Le profil de timing contrôle uniquement les temps de consultation : lecture, scan, relecture d\'un résultat trouvé. Les mouvements de souris, clics et saisies gardent leurs propres modèles humains.');
lines.push('');
lines.push('Payload `human.timing.set` :');
lines.push('');
lines.push('```json');
lines.push('{');
lines.push('  "consultSpeed": 1.6,');
lines.push('  "focusedWpmMin": 150,');
lines.push('  "focusedWpmMax": 210,');
lines.push('  "skimWpmMin": 190,');
lines.push('  "skimWpmMax": 280,');
lines.push('  "minFocusedMs": 3500,');
lines.push('  "maxFocusedMs": 60000,');
lines.push('  "minSkimMs": 1500,');
lines.push('  "maxSkimMs": 25000,');
lines.push('  "feedbackIntervalMs": 800');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('| Champ | Effet | Conseil |');
lines.push('|---|---|---|');
lines.push('| `consultSpeed` | Multiplie tous les temps de consultation | `1` normal, `1.5` plus lent, `0.75` plus rapide |');
lines.push('| `focusedWpmMin` / `focusedWpmMax` | Vitesse de lecture attentive | Baisser les WPM allonge les pauses |');
lines.push('| `skimWpmMin` / `skimWpmMax` | Vitesse de scan rapide | À garder plus haut que le focused WPM |');
lines.push('| `minFocusedMs` / `maxFocusedMs` | Bornes de pause pour `human.read` focalisé | Augmenter sur les sites sensibles |');
lines.push('| `minSkimMs` / `maxSkimMs` | Bornes de pause pour scan et recherche textuelle | Utile pour listes longues |');
lines.push('| `feedbackIntervalMs` | Fréquence des événements `human.feedback` | 500-1500 ms donne un bon retour temps réel |');
lines.push('');
lines.push('Réponse typique :');
lines.push('');
lines.push('```json');
lines.push('{');
lines.push('  "ok": true,');
lines.push('  "timing": {');
lines.push('    "consultSpeed": 1.6,');
lines.push('    "focusedWpmMin": 150,');
lines.push('    "focusedWpmMax": 210,');
lines.push('    "feedbackIntervalMs": 800');
lines.push('  }');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('### Feedback temps réel');
lines.push('');
lines.push('Pendant `human.read`, `human.scan` et `human.findText`, le bridge diffuse des événements WebSocket `human.feedback`. Ils ne remplacent pas la réponse finale de la commande : ils servent à piloter une boucle d\'agent pendant que la consultation est encore en cours.');
lines.push('');
lines.push('Exemple d\'événement :');
lines.push('');
lines.push('```json');
lines.push('{');
lines.push('  "type": "human.feedback",');
lines.push('  "payload": {');
lines.push('    "phase": "consulting",');
lines.push('    "reason": "human.scan.step.2",');
lines.push('    "elapsedMs": 2400,');
lines.push('    "remainingMs": 5200,');
lines.push('    "progress": 0.31,');
lines.push('    "step": 2,');
lines.push('    "totalSteps": 4,');
lines.push('    "timing": { "consultSpeed": 1.6, "feedbackIntervalMs": 800 }');
lines.push('  }');
lines.push('}');
lines.push('```');
lines.push('');
lines.push('Phases courantes :');
lines.push('');
lines.push('- `consulting` : pause de lecture ou relecture en cours.');
lines.push('- `consulted` : consultation terminée.');
lines.push('- `scrolling` : déplacement de page avant une nouvelle lecture.');
lines.push('- `timing.updated` / `timing.reset` : profil modifié à chaud.');
lines.push('- `antispam.ok` / `antispam.warning` : résultat d\'un check anti-spam.');
lines.push('');
lines.push('### Boucle agent recommandée');
lines.push('');
lines.push('1. Lire le profil avec `human.timing.get` au début d\'une session longue.');
lines.push('2. Après une navigation, préférer `human.read` ou `human.scan` avant de cliquer à nouveau.');
lines.push('3. Sur plusieurs `human.feedback` rapides ou une page sensible, appeler `human.timing.set` avec `consultSpeed` plus élevé et des minimums plus longs.');
lines.push('4. Appeler `human.antispam.check` après les recherches répétées, les pages de résultats, ou tout comportement inhabituel.');
lines.push('5. Si `blocked: true`, arrêter l\'automation et passer en intervention humaine. Le bridge n\'est pas conçu pour contourner les protections.');
lines.push('');
lines.push('Exemple WebSocket complet :');
lines.push('');
lines.push('```json');
lines.push('{ "id": "t1", "type": "human.timing.set", "payload": { "consultSpeed": 1.8, "minFocusedMs": 4000 } }');
lines.push('{ "id": "r1", "type": "human.read", "payload": { "focused": true } }');
lines.push('{ "id": "a1", "type": "human.antispam.check", "payload": {} }');
lines.push('```');
lines.push('');

lines.push('## Variables d\'environnement');
lines.push('');
lines.push('| Variable | Rôle | Défaut |');
lines.push('|---|---|---|');
lines.push('| `PORT` | port HTTP/WS | 8080 |');
lines.push('| `BRIDGE_HOST` | host de bind | 127.0.0.1 |');
lines.push('| `BRIDGE_URL` | URL WebSocket utilisée par le CLI TypeScript | `ws://localhost:8080/ws/browser-bridge` |');
lines.push('| `BRIDGE_TOKEN` | token d\'auth WS, obligatoire hors localhost | (vide autorisé localement) |');
lines.push('| `BRIDGE_ADMIN_TOKEN` | token pour `exec.script` | (vide = commande désactivée) |');
lines.push('| `BRIDGE_ALLOW_EXEC_SCRIPT` | active `exec.script` si `1` | 0 |');
lines.push('| `BRIDGE_ALLOW_FILE_URLS` | active navigation `file:` si `1` | 0 |');
lines.push('| `BRIDGE_ALLOWED_FILE_ROOTS` | CSV de racines autorisées pour `file:` | (vide) |');
lines.push('| `CHROME_CHANNEL` | canal navigateur Playwright (`chrome`, `chromium`, `msedge`) | chrome |');
lines.push('| `CHROME_PROFILE` | dossier de profil persistant Chromium/Chrome | (vide = contexte neuf) |');
lines.push('| `CHROME_CDP_URL` | endpoint CDP pour se connecter à un navigateur existant | (vide) |');
lines.push('| `BRIDGE_PLAYWRIGHT_SLOWMO_MS` | ralentissement Playwright appliqué aux actions bas niveau | 0 |');
lines.push('| `BRIDGE_BRING_TO_FRONT` | remet la page active au premier plan (`0` désactive) | 1 |');
lines.push('| `BRIDGE_POLITE_MODE` | ralentissement par domaine + détection anti-bot (`0` désactive) | 1 |');
lines.push('| `BRIDGE_POLITE_MIN_DELAY_MS` | délai minimum entre navigations vers le même host | 12000 |');
lines.push('| `BRIDGE_AUTO_COOKIES` | gestion automatique des bannières cookies connues (`0` désactive) | 1 |');
lines.push('| `BRIDGE_HUMAN_WARMUP` | mouvements/pauses humaines après navigation (`0` désactive) | 1 |');
lines.push('| `BRIDGE_PAGE_WARMUP_MS` | durée du warmup humain après navigation | 2500 |');
lines.push('| `BRIDGE_HUMAN_CONSULT_SPEED` | multiplicateur initial des temps de consultation humaine | `BRIDGE_DEMO_SPEED` ou 1 |');
lines.push('| `BRIDGE_DEMO_SPEED` | multiplicateur général des mouvements/pauses de démonstration | 1 |');
lines.push('| `BRIDGE_VISIBLE_CURSOR` | affiche le curseur visuel injecté (`0` désactive) | 1 |');
lines.push('| `BRIDGE_ALLOWED_ORIGINS` | CSV origines autorisées | (vide = toutes) |');
lines.push('| `BRIDGE_DEFAULT_TIMEOUT_MS` | timeout défaut Playwright | 15000 |');
lines.push('| `BRIDGE_DEFAULT_NAV_TIMEOUT_MS` | timeout nav défaut | 20000 |');
lines.push('| `BRIDGE_LOG_JSON` | logs JSON si `1` | 0 |');
lines.push('| `BRIDGE_LOG_LEVEL` | niveau min logs | info |');
lines.push('| `BRIDGE_MCP_ALLOW_RAW` | expose l\'outil MCP brut `browser_command` si `1` | 0 |');
lines.push('');

const out = join(process.cwd(), 'docs', 'api.md');
await mkdir(join(process.cwd(), 'docs'), { recursive: true });
await writeFile(out, lines.join('\n'), 'utf8');
console.log(`Wrote ${out} (${names.length} commands)`);
